/* parser generated by jison 0.4.17 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var dql = (function(){
var o=function(k,v,o,l){for(o=o||{},l=k.length;l--;o[k[l]]=v);return o},$V0=[6,8],$V1=[1,7],$V2=[1,8],$V3=[1,9],$V4=[1,12],$V5=[6,8,17,22],$V6=[1,13],$V7=[6,8,17,19,22],$V8=[6,10,14,15,24,25,26,27,28,29,32,34,36,38],$V9=[1,38],$Va=[1,39],$Vb=[1,40],$Vc=[1,41],$Vd=[33,42,43,44],$Ve=[6,10],$Vf=[6,8,10,17,19,22],$Vg=[10,22];
var parser = {trace: function trace() { },
yy: {},
symbols_: {"error":2,"main":3,"optWhereClause":4,"optOrderByClause":5,"EOF":6,"expression":7,"ORDER_BY":8,"orderByList":9,"COMMA":10,"orderByListItem":11,"identifier":12,"optOrderByOrder":13,"ASC":14,"DESC":15,"andCondition":16,"LOGICAL_OR":17,"condition":18,"LOGICAL_AND":19,"conditionRightHandSide":20,"LPAREN":21,"RPAREN":22,"compare":23,"CMP_EQUALS":24,"CMP_NOTEQUALS":25,"CMP_GREATER":26,"CMP_GREATEROREQUAL":27,"CMP_LESS":28,"CMP_LESSOREQUAL":29,"rhsCompareTest":30,"rhsInTest":31,"LIKE":32,"STRING":33,"ILIKE":34,"value":35,"IN":36,"rhsInClause":37,"LOGICAL_NOT":38,"commaSepExpressionList":39,"IDENTIFIER":40,"QUALIFIED_IDENTIFIER":41,"NUMERIC":42,"BOOLEAN":43,"NULL":44,"$accept":0,"$end":1},
terminals_: {2:"error",6:"EOF",8:"ORDER_BY",10:"COMMA",14:"ASC",15:"DESC",17:"LOGICAL_OR",19:"LOGICAL_AND",21:"LPAREN",22:"RPAREN",24:"CMP_EQUALS",25:"CMP_NOTEQUALS",26:"CMP_GREATER",27:"CMP_GREATEROREQUAL",28:"CMP_LESS",29:"CMP_LESSOREQUAL",32:"LIKE",33:"STRING",34:"ILIKE",36:"IN",38:"LOGICAL_NOT",40:"IDENTIFIER",41:"QUALIFIED_IDENTIFIER",42:"NUMERIC",43:"BOOLEAN",44:"NULL"},
productions_: [0,[3,3],[4,0],[4,1],[5,0],[5,2],[9,3],[9,1],[11,2],[13,0],[13,1],[13,1],[7,1],[7,3],[16,1],[16,3],[18,2],[18,3],[23,1],[23,1],[23,1],[23,1],[23,1],[23,1],[20,1],[20,1],[30,2],[30,2],[30,2],[31,4],[31,5],[37,3],[39,3],[39,1],[12,1],[12,1],[35,1],[35,1],[35,1],[35,1]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 1:
 return {where: $$[$0-2], orderBy: $$[$0-1]}; 
break;
case 2: case 4: case 39:
 this.$ = null; 
break;
case 3: case 5: case 10: case 11: case 12: case 14: case 24: case 25: case 34: case 35:
 this.$ = $$[$0]; 
break;
case 6:
 this.$ = $$[$0-2]; this.$[$$[$0].identifier] = $$[$0].direction.toLowerCase() === 'desc' ? -1 : 1; 
break;
case 7:
 this.$ = {}; this.$[$$[$0].identifier] = $$[$0].direction.toLowerCase() === 'desc' ? -1 : 1; 
break;
case 8:
 this.$ = {identifier:$$[$0-1], direction: $$[$0]}; 
break;
case 9:
 this.$ = ''; 
break;
case 13:
 this.$ = Array.isArray($$[$0-2].$or) ? $$[$0-2] : {$or: [$$[$0-2]]}; this.$.$or.push($$[$0]); 
break;
case 15:
 this.$ = Array.isArray($$[$0-2].$and) ? $$[$0-2] : {$and: [$$[$0-2]]}; this.$.$and.push($$[$0]); 
break;
case 16:
 this.$ = yy.transform ? yy.transform($$[$0-1], $$[$0].operator, $$[$0].value) : null; if (!this.$) { this.$ = {}; if ($$[$0].operator === '$eq') { this.$[$$[$0-1]] = $$[$0].value; } else { this.$[$$[$0-1]] = {}; this.$[$$[$0-1]][$$[$0].operator] = $$[$0].value; } } 
break;
case 17:
 this.$ = $$[$0-1]; 
break;
case 18:
 this.$ = '$eq'; 
break;
case 19:
 this.$ = '$ne'; 
break;
case 20:
 this.$ = '$gt'; 
break;
case 21:
 this.$ = '$gte'; 
break;
case 22:
 this.$ = '$lt'; 
break;
case 23:
 this.$ = '$lte'; 
break;
case 26:
 this.$ = {operator: '$regex', value: new RegExp($$[$0].substring(1, $$[$0].length - 1))}; 
break;
case 27:
 this.$ = {operator: '$regex', value: new RegExp($$[$0].substring(1, $$[$0].length - 1), 'i')}; 
break;
case 28:
 this.$ = {operator: $$[$0-1], value: $$[$0]}; 
break;
case 29:
 this.$ = {operator: '$in', value: $$[$0-1]}; 
break;
case 30:
 this.$ = {operator: '$nin', value: $$[$0-1]}; 
break;
case 31:
 this.$ = $$[$0]; $$[$0].unshift($$[$0-2]); 
break;
case 32:
 this.$ = $$[$0-2]; $$[$0-2].push($$[$0]); 
break;
case 33:
 this.$ = [$$[$0]]; 
break;
case 36:
 this.$ = $$[$0].substring(1, $$[$0].length - 1); 
break;
case 37:
 this.$ = parseFloat($$[$0]); 
break;
case 38:
 this.$ = $$[$0].toLowerCase() === 'true'; 
break;
}
},
table: [o($V0,[2,2],{3:1,4:2,7:3,16:4,18:5,12:6,21:$V1,40:$V2,41:$V3}),{1:[3]},{5:10,6:[2,4],8:[1,11]},o($V0,[2,3],{17:$V4}),o($V5,[2,12],{19:$V6}),o($V7,[2,14]),{20:14,23:19,24:[1,22],25:[1,23],26:[1,24],27:[1,25],28:[1,26],29:[1,27],30:15,31:16,32:[1,17],34:[1,18],36:[1,20],38:[1,21]},{7:28,12:6,16:4,18:5,21:$V1,40:$V2,41:$V3},o($V8,[2,34]),o($V8,[2,35]),{6:[1,29]},{9:30,11:31,12:32,40:$V2,41:$V3},{12:6,16:33,18:5,21:$V1,40:$V2,41:$V3},{12:6,18:34,21:$V1,40:$V2,41:$V3},o($V7,[2,16]),o($V7,[2,24]),o($V7,[2,25]),{33:[1,35]},{33:[1,36]},{33:$V9,35:37,42:$Va,43:$Vb,44:$Vc},{21:[1,42]},{36:[1,43]},o($Vd,[2,18]),o($Vd,[2,19]),o($Vd,[2,20]),o($Vd,[2,21]),o($Vd,[2,22]),o($Vd,[2,23]),{17:$V4,22:[1,44]},{1:[2,1]},{6:[2,5],10:[1,45]},o($Ve,[2,7]),o($Ve,[2,9],{13:46,14:[1,47],15:[1,48]}),o($V5,[2,13],{19:$V6}),o($V7,[2,15]),o($V7,[2,26]),o($V7,[2,27]),o($V7,[2,28]),o($Vf,[2,36]),o($Vf,[2,37]),o($Vf,[2,38]),o($Vf,[2,39]),{33:$V9,35:50,37:49,42:$Va,43:$Vb,44:$Vc},{21:[1,51]},o($V7,[2,17]),{11:52,12:32,40:$V2,41:$V3},o($Ve,[2,8]),o($Ve,[2,10]),o($Ve,[2,11]),{22:[1,53]},{10:[1,54]},{33:$V9,35:50,37:55,42:$Va,43:$Vb,44:$Vc},o($Ve,[2,6]),o($V7,[2,29]),{33:$V9,35:57,39:56,42:$Va,43:$Vb,44:$Vc},{22:[1,58]},{10:[1,59],22:[2,31]},o($Vg,[2,33]),o($V7,[2,30]),{33:$V9,35:60,42:$Va,43:$Vb,44:$Vc},o($Vg,[2,32])],
defaultActions: {29:[2,1]},
parseError: function parseError(str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        function _parseError (msg, hash) {
            this.message = msg;
            this.hash = hash;
        }
        _parseError.prototype = Error;

        throw new _parseError(str, hash);
    }
},
parse: function parse(input) {
    var self = this, stack = [0], tstack = [], vstack = [null], lstack = [], table = this.table, yytext = '', yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
    var args = lstack.slice.call(arguments, 1);
    var lexer = Object.create(this.lexer);
    var sharedState = { yy: {} };
    for (var k in this.yy) {
        if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
            sharedState.yy[k] = this.yy[k];
        }
    }
    lexer.setInput(input, sharedState.yy);
    sharedState.yy.lexer = lexer;
    sharedState.yy.parser = this;
    if (typeof lexer.yylloc == 'undefined') {
        lexer.yylloc = {};
    }
    var yyloc = lexer.yylloc;
    lstack.push(yyloc);
    var ranges = lexer.options && lexer.options.ranges;
    if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    _token_stack:
        var lex = function () {
            var token;
            token = lexer.lex() || EOF;
            if (typeof token !== 'number') {
                token = self.symbols_[token] || token;
            }
            return token;
        };
    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            action = table[state] && table[state][symbol];
        }
                    if (typeof action === 'undefined' || !action.length || !action[0]) {
                var errStr = '';
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push('\'' + this.terminals_[p] + '\'');
                    }
                }
                if (lexer.showPosition) {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ':\n' + lexer.showPosition() + '\nExpecting ' + expected.join(', ') + ', got \'' + (this.terminals_[symbol] || symbol) + '\'';
                } else {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ': Unexpected ' + (symbol == EOF ? 'end of input' : '\'' + (this.terminals_[symbol] || symbol) + '\'');
                }
                this.parseError(errStr, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected
                });
            }
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol);
        }
        switch (action[0]) {
        case 1:
            stack.push(symbol);
            vstack.push(lexer.yytext);
            lstack.push(lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
                yyleng = lexer.yyleng;
                yytext = lexer.yytext;
                yylineno = lexer.yylineno;
                yyloc = lexer.yylloc;
                if (recovering > 0) {
                    recovering--;
                }
            } else {
                symbol = preErrorSymbol;
                preErrorSymbol = null;
            }
            break;
        case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
                first_line: lstack[lstack.length - (len || 1)].first_line,
                last_line: lstack[lstack.length - 1].last_line,
                first_column: lstack[lstack.length - (len || 1)].first_column,
                last_column: lstack[lstack.length - 1].last_column
            };
            if (ranges) {
                yyval._$.range = [
                    lstack[lstack.length - (len || 1)].range[0],
                    lstack[lstack.length - 1].range[1]
                ];
            }
            r = this.performAction.apply(yyval, [
                yytext,
                yyleng,
                yylineno,
                sharedState.yy,
                action[1],
                vstack,
                lstack
            ].concat(args));
            if (typeof r !== 'undefined') {
                return r;
            }
            if (len) {
                stack = stack.slice(0, -1 * len * 2);
                vstack = vstack.slice(0, -1 * len);
                lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
        case 3:
            return true;
        }
    }
    return true;
}};
/* generated by jison-lex 0.3.4 */
var lexer = (function(){
var lexer = ({

EOF:1,

parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },

// resets the lexer, sets new input
setInput:function (input, yy) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0,0];
        }
        this.offset = 0;
        return this;
    },

// consumes and returns one char from the input
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
    },

// unshifts one char (or a string) into the input
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                 + oldLines[oldLines.length - lines.length].length - lines[0].length :
              this.yylloc.first_column - len
        };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    },

// When called from action, caches matched text and appends it on next action
more:function () {
        this._more = true;
        return this;
    },

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function () {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });

        }
        return this;
    },

// retain first n characters of the match
less:function (n) {
        this.unput(this.match.slice(n));
    },

// displays already matched input, i.e. for error messages
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },

// displays upcoming input, i.e. for error messages
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20) + (next.length > 20 ? '...' : '')).replace(/\n/g, "");
    },

// displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
    },

// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function (match, indexed_rule) {
        var token,
            lines,
            backup;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
    },

// return next match in input
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }

        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
    },

// return next match that has a token
lex:function lex() {
        var r = this.next();
        if (r) {
            return r;
        } else {
            return this.lex();
        }
    },

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function begin(condition) {
        this.conditionStack.push(condition);
    },

// pop the previously active lexer condition state off the condition stack
popState:function popState() {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },

// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function _currentRules() {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions["INITIAL"].rules;
        }
    },

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function topState(n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return "INITIAL";
        }
    },

// alias for begin(condition)
pushState:function pushState(condition) {
        this.begin(condition);
    },

// return the number of states currently on the stack
stateStackSize:function stateStackSize() {
        return this.conditionStack.length;
    },
options: {"case-insensitive":true},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START) {
var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0:/* skip comments */
break;
case 1:return 41
break;
case 2:/* skip whitespace */
break;
case 3:return 8
break;
case 4:return 10
break;
case 5:return 24
break;
case 6:return 25
break;
case 7:return 27
break;
case 8:return 26
break;
case 9:return 29
break;
case 10:return 28
break;
case 11:return 21
break;
case 12:return 22
break;
case 13:return 32
break;
case 14:return 34
break;
case 15:return 36
break;
case 16:return 19
break;
case 17:return 17
break;
case 18:return 38
break;
case 19:return 14
break;
case 20:return 15
break;
case 21:return 33
break;
case 22:return 44
break;
case 23:return 43
break;
case 24:return 42
break;
case 25:return 40
break;
case 26:return 'BIND'
break;
case 27:return 6
break;
case 28:return 'INVALID'
break;
}
},
rules: [/^(?:[\/][*](.|\n)*?[*][\/])/i,/^(?:[a-zA-Z_][a-zA-Z0-9_]*\.[a-zA-Z_][a-zA-Z0-9_]*)/i,/^(?:\s+)/i,/^(?:ORDER\s+BY\b)/i,/^(?:,)/i,/^(?:=)/i,/^(?:!=)/i,/^(?:>=)/i,/^(?:>)/i,/^(?:<=)/i,/^(?:<)/i,/^(?:\()/i,/^(?:\))/i,/^(?:LIKE\b)/i,/^(?:ILIKE\b)/i,/^(?:IN\b)/i,/^(?:AND\b)/i,/^(?:OR\b)/i,/^(?:NOT\b)/i,/^(?:ASC\b)/i,/^(?:DESC\b)/i,/^(?:['](\\.|[^'])*['])/i,/^(?:NULL\b)/i,/^(?:(true|false)\b)/i,/^(?:[0-9]+(\.[0-9]+)?)/i,/^(?:[a-zA-Z_][a-zA-Z0-9_]*)/i,/^(?:[?])/i,/^(?:$)/i,/^(?:.)/i],
conditions: {"INITIAL":{"rules":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28],"inclusive":true}}
});
return lexer;
})();
parser.lexer = lexer;
function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = dql;
exports.Parser = dql.Parser;
exports.parse = function () { return dql.parse.apply(dql, arguments); };
exports.main = function commonjsMain(args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}